#!/bin/sh

# PROVIDE: hw4
# REQUIRE: networking
# KEYWORD: shutdown

. /etc/rc.subr

name="hw4"
rcvar=${name}_enable

load_rc_config $name

start_cmd="${name}_start"
stop_cmd="${name}_stop"
restart_cmd="${name}_restart"

hw4_start()
{
	cd /home/Colten/musical-potato/
	poetry shell
	cd api && poetry run uvicorn app:APP --reload --host 0.0.0.0

}
hw4_stop()
{
    echo "Stopping hw4"
    
    if [ -f "/ver/run/hw4.pid" ]; then
	    kill $(cat /var/run/hw4.pid)
	    rm /var/run/hw4.pid
    fi
}
hw4_restart()
{
    hw4_stop
    hw4_start
}

load_rc_config $name

run_rc_command "$1"

